version: "3"

services:

  db:
    image: mysql:5.6
    env_file:
      - env.d/ci/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci


  # As mentionned in ElasticSearch's documentation [1], "it is important to ensure
  # increased ulimits for nofile and nproc are available for the Elasticsearch
  # containers [...]  if needed, adjust them in the Daemon, or override them per
  # container".
  #
  # [1] https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
  elasticsearch:
    image: fundocker/openshift-elasticsearch:6.6.2
    ulimits:
      memlock:
        soft: -1
        hard: -1

  app:
    image: "richie:${CIRCLE_SHA1}${IMAGE_SUFFIX}-ci"
    env_file:
      - env.d/ci/common
      - env.d/ci/mysql
    depends_on:
      - "db"
      - "elasticsearch"
    tmpfs: /data:uid=1000
