# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 14:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0020_old_tree_cleanup"), ("courses", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="OrganizationPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="courses_organizationpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.Organization",
                    ),
                ),
            ],
            options={"verbose_name": "organization plugin model"},
            bases=("cms.cmsplugin",),
        )
    ]
