# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0002_organizationpluginmodel")]

    operations = [migrations.RemoveField(model_name="organization", name="logo")]
