# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 10:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0004_licence_licencepluginmodel")]

    operations = [
        migrations.CreateModel(
            name="CourseRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Resource link"
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="course start"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="course end"
                    ),
                ),
                (
                    "enrollment_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enrollment start"
                    ),
                ),
                (
                    "enrollment_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enrollment end"
                    ),
                ),
            ],
            options={"verbose_name": "course run"},
        ),
        migrations.RemoveField(model_name="course", name="active_session"),
        migrations.AlterField(
            model_name="licence",
            name="content",
            field=models.TextField(default="", verbose_name="content"),
        ),
        migrations.AddField(
            model_name="courserun",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.Course",
                verbose_name="course",
            ),
        ),
    ]
