# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 16:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0005_auto_20180830_1217")]

    operations = [
        migrations.AlterField(
            model_name="organizationpluginmodel",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugin_model",
                to="courses.Organization",
            ),
        )
    ]
