# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 20:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0005_add_course_run")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_run",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_run",
                to="courses.CourseRun",
            ),
            preserve_default=False,
        )
    ]
