# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0006_course_course_run")]

    operations = [
        migrations.RemoveField(model_name="course", name="course_run"),
        migrations.AddField(
            model_name="course",
            name="course_run",
            field=models.ManyToManyField(
                related_name="course_run", to="courses.CourseRun"
            ),
        ),
    ]
