# Generated by Django 3.1.7 on 2021-02-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20210126_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='effort',
            new_name='pace',
        ),
    ]
