# Generated by Django 3.2.9 on 2021-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0032_auto_20211004_1733"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="catalog_visibility",
            field=models.CharField(
                choices=[
                    (
                        "course_and_search",
                        "course_and_search - show on the course page and include in search results",
                    ),
                    (
                        "course_only",
                        "course_only - show on the course page and hide from search results",
                    ),
                    (
                        "hidden",
                        "hidden - hide on the course page and from search results",
                    ),
                ],
                default="course_and_search",
                max_length=20,
                verbose_name="catalog visibility",
            ),
        ),
    ]
