# Generated by Django 3.2.9 on 2021-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_auto_20211004_1733"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="catalog_visibility",
            field=models.CharField(
                choices=[
                    ("both", "both - show in catalog and allow access to about page"),
                    ("about", "about - only allow access to about page"),
                    (
                        "none",
                        "none - do not show in catalog and do not allow access to an about page",
                    ),
                ],
                default="both",
                max_length=5,
                verbose_name="catalog visibility",
            ),
        ),
    ]
