# Generated by Django 4.2.14 on 2024-09-09 15:06

import django.db.models.deletion
from django.db import migrations, models

from ..defaults import INDEX_MENU_COLOR_CLASSES


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("courses", "0034_auto_20230817_1736"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_submenu",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled the page entry in menu will be a dropdown for its possible children.",
                        verbose_name="Allow submenu",
                    ),
                ),
                (
                    "menu_color",
                    models.CharField(
                        blank=True,
                        choices=INDEX_MENU_COLOR_CLASSES,
                        default="",
                        help_text="A color used to display page in menu",
                        max_length=10,
                        verbose_name="Color in menu",
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.page",
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="courses.indexpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "index",
                "verbose_name_plural": "indexes",
                "db_table": "richie_index",
                "ordering": ["-pk"],
            },
        ),
    ]
