# Generated by Django 4.2.13 on 2024-07-09 10:56

from django.db import migrations, models

import richie.apps.core.fields.multiselect


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0034_auto_20230817_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="offer",
            field=models.CharField(
                choices=[
                    (
                        "free",
                        "free - The entire course can be completed without cost",
                    ),
                    (
                        "partially_free",
                        "partially_free - More than half of the course is for free",
                    ),
                    (
                        "subscription",
                        "subscription - The user must be a subscriber or paid member in order to complete the entire course",
                    ),
                    (
                        "paid",
                        "paid - The user must pay to complete the course",
                    ),
                ],
                default="free",
                max_length=20,
                verbose_name="offer",
            ),
        ),
    ]
