# Generated by Django 4.2.13 on 2024-07-09 14:37

from django.db import migrations, models

import richie.apps.core.fields.multiselect


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0035_courserun_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="price",
            field=models.FloatField(
                default=0.0, help_text="The cost of the course", verbose_name="price"
            ),
        ),
    ]
