# Generated by Django 4.2.16 on 2024-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0035_courserun_certificate_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="certificate_price_editable",
            field=models.BooleanField(
                default=False, verbose_name="certificate price is editable"
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="price_editable",
            field=models.BooleanField(default=False, verbose_name="price is editable"),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="certificate_offer",
            field=models.CharField(
                choices=[
                    ("free", "free - The certification can be completed without cost"),
                    (
                        "subscription",
                        "subscription - Must be a subscriber or paid member to carry out the certification process",
                    ),
                    ("paid", "paid - Must pay to carry out the certification process"),
                ],
                default="free",
                max_length=20,
                verbose_name="certificate_offer",
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="offer",
            field=models.CharField(
                choices=[
                    ("free", "free - The entire course can be completed without cost"),
                    (
                        "partially_free",
                        "partially_free - More than half of the course is for free",
                    ),
                    (
                        "subscription",
                        "subscription - Must be a subscriber or paid member to complete the entire course",
                    ),
                    ("paid", "paid - Must pay to complete the course"),
                ],
                default="free",
                max_length=20,
                verbose_name="offer",
            ),
        ),
    ]
