# Generated by Django 4.2.21 on 2025-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_program_duration_program_effort_program_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="discount",
            field=models.CharField(
                blank=True,
                help_text="The discount applied to the course run",
                max_length=20,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The discounted price of the course run",
                max_digits=9,
                null=True,
                verbose_name="discounted price",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_listed",
            field=models.BooleanField(
                default=True,
                help_text="Tick if you want the course to be visible.",
                verbose_name="is listed",
            ),
        ),
    ]
