# Generated by Django 4.2.16 on 2024-11-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("glimpse", "0003_auto_20201118_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glimpse",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="glimpse",
            name="variant",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inherit"),
                    ("badge", "Badge"),
                    ("card_square", "Square card"),
                    ("person", "Person"),
                    ("quote", "Quote"),
                    ("row_half", "Half row"),
                    ("row_full", "Full row"),
                ],
                default=None,
                help_text="Form factor variant",
                max_length=50,
                null=True,
                verbose_name="Variant",
            ),
        ),
    ]
