version: 2
jobs:

  build-back:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/richie
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-back-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v3-back-dependencies-
      - run:
          name: Install back-end dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v3-back-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}

  build-front:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-front-dependencies-{{ checksum "package.json" }}
          - v3-front-dependencies-
      - run:
          name: Install front-end dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build front-end application
          command: yarn build
      - run:
          name: Build application styles
          command: yarn sass
      - save_cache:
          paths:
            - ./node_modules
          key: v3-front-dependencies-{{ checksum "package.json" }}

  lint-back-flake8:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-back-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Lint code with flake8
          command: |
            . venv/bin/activate
            flake8

  lint-back-pylint:
    docker:
      - image: python:3.6-stretch
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-back-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Lint code with pylint
          command: |
            . venv/bin/activate
            pylint apps plugins richie

  lint-front:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-front-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint code with tslint
          command: yarn lint

  test-back:
    docker:
      - image: python:3.6-stretch
        environment:
          DJANGO_SETTINGS_MODULE: 'richie.settings'
          DJANGO_CONFIGURATION: 'ContinuousIntegration'
          DJANGO_SECRET_KEY: 'ThisIsAnExampleKeyForCIPurposeOnly'
          POSTGRES_HOST: '127.0.0.1'
          POSTGRES_DB: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: ''
      - image: postgres:9.6
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-back-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  test-front:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/richie
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-front-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test --single-run

workflows:
  version: 2

  richie:
    jobs:
      - build-back:
          filters:
            tags:
              only: /.*/
      - build-front:
          filters:
            tags:
              only: /.*/
      - lint-back-flake8:
          requires:
            - build-back
          filters:
            tags:
              only: /.*/
      - lint-back-pylint:
          requires:
            - build-back
          filters:
            tags:
              only: /.*/
      - lint-front:
          requires:
            - build-front
          filters:
            tags:
              only: /.*/
      - test-back:
          requires:
            - build-back
          filters:
            tags:
              only: /.*/
      - test-front:
          requires:
            - build-front
          filters:
            tags:
              only: /.*/
