# Generated by Django 4.2.16 on 2024-11-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_text_ckeditor", "0002_add_variant_and_cmsplugin_ptr"),
        ("simple_text_ckeditor", "0002_alter_simpletext_cmsplugin_ptr"),
    ]

    operations = []
