# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("cms", "0018_pagenode"), ("organizations", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active_session",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Course key of active course session",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={"verbose_name": "course"},
        ),
        migrations.CreateModel(
            name="CourseOrganizationRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Rank"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_organizations",
                        to="courses.Course",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_courses",
                        to="organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "course-organization relation",
                "ordering": ("rank", "id"),
            },
        ),
        migrations.CreateModel(
            name="CoursePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_pages",
                        to="courses.Course",
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.Page",
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="courses.CoursePage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CourseSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                )
            ],
            options={"verbose_name": "course subject"},
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CourseSubjectPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.Page",
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="courses.CourseSubjectPage",
                    ),
                ),
                (
                    "course_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_subject_pages",
                        to="courses.CourseSubject",
                    ),
                ),
            ],
            options={"abstract": False, "verbose_name": "course subject page"},
        ),
        migrations.CreateModel(
            name="CourseSubjectTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Displayed where space is rare - on side panel for instance.",
                        max_length=255,
                        null=True,
                        verbose_name="short name",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="courses.CourseSubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "course subject Translation",
                "db_table": "courses_coursesubject_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="organizations",
            field=models.ManyToManyField(
                related_name="courses",
                through="courses.CourseOrganizationRelation",
                to="organizations.Organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subjects",
            field=models.ManyToManyField(
                related_name="courses", to="courses.CourseSubject"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursesubjecttranslation",
            unique_together=set([("language_code", "master")]),
        ),
        migrations.AlterUniqueTogether(
            name="courseorganizationrelation",
            unique_together=set([("course", "organization"), ("course", "rank")]),
        ),
        migrations.AlterModelOptions(
            name="courseorganizationrelation",
            options={
                "ordering": ("course", "rank"),
                "verbose_name": "course-organization relation",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="active_session",
            field=models.CharField(
                db_index=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Course key of active course session",
            ),
        ),
    ]
