# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="course", old_name="title", new_name="name")
    ]
