# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 09:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("cms", "0020_old_tree_cleanup")]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="section_section",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        )
    ]
