# Generated by Django 4.2.16 on 2024-10-11 21:01

import django.db.models.deletion
from django.db import migrations, models

from ..defaults import SECTION_GRID_COLUMNS


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("section", "0006_add_attributes_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="grid_columns",
            field=models.CharField(
                blank=True,
                choices=SECTION_GRID_COLUMNS,
                default="",
                help_text="Define a Grid to use for contents, when no Grid is enable each content can define its own width.",
                max_length=50,
                verbose_name="Grid",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="grid_gutter",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Enable a gutter between content items when Grid is enabled.",
                verbose_name="Grid gutter",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
