# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organization_organization', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('short_name', models.CharField(blank=True, help_text='Displayed where space is rare - on side panel for instance.', max_length=255, verbose_name='short name')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('certificate_logo', models.ImageField(blank=True, help_text='Logo to be displayed on the certificate document.', null=True, upload_to='Organization', verbose_name='certificate logo')),
                ('logo', models.ImageField(upload_to='Organization', verbose_name='logo')),
                ('is_detail_page_enabled', models.BooleanField(db_index=True, default=False, help_text='Enables the university detail page.', verbose_name='detail page enabled')),
                ('is_obsolete', models.BooleanField(db_index=True, default=False, help_text='Obsolete Organization do not have their logo displayed on the site.', verbose_name='is obsolete')),
                ('slug', models.SlugField(help_text='Only used if detail page is enabled', max_length=255, unique=True, verbose_name='slug')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Organization', verbose_name='banner')),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('partnership_level', models.CharField(blank=True, choices=[('simple_partner', 'Partner'), ('academic_partner', 'Academic Partner'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], db_index=True, max_length=255, verbose_name='partnership level')),
                ('score', models.PositiveIntegerField(db_index=True, default=0, verbose_name='score')),
            ],
            options={
                'verbose_name': 'Organization',
                'ordering': ('-score', 'id'),
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OrganizationList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organization_organizationlist', serialize=False, to='cms.CMSPlugin')),
                ('limit', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
