"""Customizing Django storage backends to enable blue/green deployments."""
import re
from collections import OrderedDict

from django.conf import settings
from django.contrib.staticfiles.storage import ManifestFilesMixin, StaticFilesStorage

from storages.backends.s3boto3 import S3Boto3Storage

STATIC_POSTPROCESS_IGNORE_REGEX = re.compile(r"^richie\/js\/[0-9]*\..*\.index\.js$")


class ConfigurableManifestFilesMixin(ManifestFilesMixin):
    """Allow configuring the name of the manifest file via Django settings."""

    manifest_name = settings.STATICFILES_MANIFEST_NAME

    def post_process(self, paths, dry_run=False, **options):
        """Remove paths from file to post process.
        Some js static files generated by webpack already have a unique name per build
        and may be referenced from within the js applications. We therefore don't want
        to hash their name and include them in the manifest file.
        We use a regex configurable via settings to decide which files to ignore.
        Parameters
        ----------
        paths : OrderedDict
            List of files to post process
        dry_run: boolean
            run process but nothing is apply if True
        options: kwargs
            See HashedFilesMixin.post_process
        """
        filtered_paths = OrderedDict()
        for path in paths:
            if not STATIC_POSTPROCESS_IGNORE_REGEX.match(path):
                filtered_paths[path] = paths[path]

        yield from super().post_process(filtered_paths, dry_run=dry_run, **options)


class ConfigurableManifestStaticFilesStorage(
    ConfigurableManifestFilesMixin, StaticFilesStorage
):
    """A ManifestStaticFilesStorage backend with configurable manifest file name.
    A static file system storage backend which saves files on the filesystem with unique names
    derived from their content. The name of the manifest file is configurable.
    """

    pass


class ConfigurableManifestS3Boto3Storage(
    ConfigurableManifestFilesMixin, S3Boto3Storage
):
    """A S3Boto3Storage backend to serve static files via CloudFront with blue/green deployments.

    A static file system storage backend which saves files on AWS S3 with unique names
    derived from their content. The name of the manifest file is configurable to allow blue/green
    deployments.
    """

    bucket_name = settings.AWS_STATIC_BUCKET_NAME
    custom_domain = settings.AWS_CLOUDFRONT_DOMAIN
    location = settings.STATIC_URL


class MediaStorage(S3Boto3Storage):
    """A S3Boto3Storage backend to serve media files via CloudFront."""

    bucket_name = settings.AWS_MEDIA_BUCKET_NAME
    custom_domain = settings.AWS_CLOUDFRONT_DOMAIN
    file_overwrite = False
    location = settings.MEDIA_URL
