# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Organization name')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Organization code')),
                ('logo', models.ImageField(blank=True, help_text='Recommended size: 180x100', upload_to='organizations/logo/', verbose_name='Organization logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationpage',
            name='organization_key',
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='organizations.Organization'),
        ),
    ]
