# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20180418_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='organizations.Organization'),
        ),
    ]
