# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20180418_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Organization code'),
        ),
    ]
