# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180418_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationpage', to='organizations.Organization'),
        ),
    ]
