export default {
  count: 131,
  previous: null,
  num_pages: 1,
  results: [
    {
      id: 240,
      name: "HESAM Université",
      code: "hesam",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_heSam_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/heSam_illustration_FUN_2.jpg",
    },
    {
      id: 160,
      name: "Université Paris-Saclay",
      code: "ParisSaclay",
      logo: "https://www.fun-mooc.fr/media/universities/logo-paris-saclay-170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Banniere_UP-Saclay.png",
    },
    {
      id: 58,
      name: "Paris Sciences Lettres",
      code: "psl",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO_PSL_typoCERA_INDIGO_RVB_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/baniere-PSL-2.jpg",
    },
    {
      id: 1,
      name: "Le Cnam",
      code: "CNAM",
      logo: "https://www.fun-mooc.fr/media/universities/cnam_logo.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Le_Cnam_facade.jpg",
    },
    {
      id: 5,
      name: "IMT",
      code: "MinesTelecom",
      logo: "https://www.fun-mooc.fr/media/universities/IMT_logo-pour-FUN_I1bSJma.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/baniere_imt_EDX-02-02.jpg",
    },
    {
      id: 198,
      name: "Université Sorbonne Paris Cité",
      code: "USPC",
      logo: "https://www.fun-mooc.fr/media/universities/LogoUSPC_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Recherche_montaGabirelle-3.jpg",
    },
    {
      id: 42,
      name: "Inria",
      code: "inria",
      logo: "https://www.fun-mooc.fr/media/universities/INRIA-180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_MoocInria.0124-121.jpg",
    },
    {
      id: 172,
      name: "Université de Lyon",
      code: "universite-lyon",
      logo: "https://www.fun-mooc.fr/media/universities/UDL_logo_couleur-01_180x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_fun_UdL.jpg",
    },
    {
      id: 14,
      name: "ENS Paris-Saclay",
      code: "ENSCachan",
      logo: "https://www.fun-mooc.fr/media/universities/logo_180_100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/enscachan.921fde30c904.jpg",
    },
    {
      id: 188,
      name: "Université Fédérale Toulouse Midi-Pyrénées",
      code: "univ-toulouse",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-UTFTMP_horizontale_O_180x99.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/presentationMOOC-UFTMP.jpg",
    },
    {
      id: 113,
      name: "Agreenium",
      code: "Agreenium",
      logo: "https://www.fun-mooc.fr/media/universities/Agreenium_logo_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Banniere-Fixe-04.jpg",
    },
    {
      id: 8,
      name: "Université de Montpellier",
      code: "umontpellier",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-etablissement_vhkxFYa.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Photo-campus_rlrvHDS.png",
    },
    {
      id: 9,
      name: "Université Panthéon-Assas, Paris II",
      code: "Paris2",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO_PantheonAssas_sansFond_170x110p_MLiBlbk.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/paris2.e025b3182afe.jpg",
    },
    {
      id: 201,
      name: "Communauté Université Grenoble Alpes",
      code: "grenoblealpes",
      logo: "https://www.fun-mooc.fr/media/universities/logo_COMUE_Grenoble_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/campus_bu-001.jpg",
    },
    {
      id: 11,
      name: "Groupe INSA",
      code: "groupeinsa",
      logo: "https://www.fun-mooc.fr/media/universities/logoGroupeInsa_5.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/groupeinsa.3d33fea5c0b6.jpg",
    },
    {
      id: 179,
      name: "Centre national de la fonction publique territoriale (CNFPT)",
      code: "CNFPT",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_CNFPT_transparent.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Bandeau_CNFPT_original.jpg",
    },
    {
      id: 225,
      name: "ComUE Lille Nord de France",
      code: "cuelnf",
      logo: "https://www.fun-mooc.fr/media/universities/logo-CUE-Quadri180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_mooc.jpg",
    },
    {
      id: 286,
      name: "ADEME",
      code: "ADEME",
      logo: "https://www.fun-mooc.fr/media/universities/LogoAdemeFC.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/msg1.jpg",
    },
    {
      id: 249,
      name: "Université Bretagne Loire",
      code: "u-bretagneloire",
      logo: "https://www.fun-mooc.fr/media/universities/logo_UBL_RVBnoir.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeauUBL.png",
    },
    {
      id: 6,
      name: "Sciences Po.",
      code: "SciencesPo",
      logo: "https://www.fun-mooc.fr/media/universities/sciencespo.a373fc2e097a_1_k4ifYVW.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/sciencespo.21764b4b23e5.jpg",
    },
    {
      id: 72,
      name: "Université de Nantes",
      code: "univnantes",
      logo: "https://www.fun-mooc.fr/media/universities/logo-un.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/photo-illustration-un_copie.png",
    },
    {
      id: 195,
      name: "ComUE d’Aquitaine",
      code: "cuea",
      logo: "https://www.fun-mooc.fr/media/universities/image001.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_UCA_sophiatech980x200_srG4HiF.jpg",
    },
    {
      id: 39,
      name: "Université Paris-Sud",
      code: "UPSUD",
      logo: "https://www.fun-mooc.fr/media/universities/paris11.179729acb398_2.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/paris11.ea38002e63b9_1.jpg",
    },
    {
      id: 43,
      name: "Ecole Nationale Supérieure d’Arts et Métiers",
      code: "ensam",
      logo: "https://www.fun-mooc.fr/media/universities/AM-ParisTech-logo.jpeg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Angers-2013-cour_ecole__etudiants_-_0613_M.jpg_1.jpeg",
    },
    {
      id: 81,
      name: "Université Jean Moulin Lyon 3",
      code: "lyon3",
      logo: "https://www.fun-mooc.fr/media/universities/UDL-Lyon3_WEB.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/JeanMoulin1.jpg",
    },
    {
      id: 87,
      name: "Université de Lille 1, Sciences et technologies",
      code: "lille1",
      logo: "https://www.fun-mooc.fr/media/universities/logo-lille1-180x110_FUN.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/VisuelUnivLille199.jpg",
    },
    {
      id: 108,
      name: "Université Paris Diderot",
      code: "parisdiderot",
      logo: "https://www.fun-mooc.fr/media/universities/LogoParisDiderot_170x110px.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/FUN-MOOC_Paris_Diderot.jpg",
    },
    {
      id: 170,
      name: "MINES ParisTech",
      code: "ENSMP",
      logo: "https://www.fun-mooc.fr/media/universities/logominesparis_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banni%C3%A8re.jpg",
    },
    {
      id: 46,
      name: "Normandie Université",
      code: "unormandie",
      logo: "https://www.fun-mooc.fr/media/universities/logo_unormandie_170.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/illustration_normandie_universit%C3%A9.jpg",
    },
    {
      id: 52,
      name: "Université de Bordeaux",
      code: "ubordeaux",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO-UBX-170X110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/UBx-980X200.jpg",
    },
    {
      id: 136,
      name: "Observatoire de Paris",
      code: "OBSPM",
      logo: "https://www.fun-mooc.fr/media/universities/logo-obspm.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere-obspm.png",
    },
    {
      id: 163,
      name: "Université de Bourgogne",
      code: "ubourgogne",
      logo: "https://www.fun-mooc.fr/media/universities/logo_uB_orange_filet_-_166c-170x109.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/uB_banni%C3%A8re.jpg",
    },
    {
      id: 167,
      name: "Université Paris Descartes",
      code: "parisdescartes",
      logo: "https://www.fun-mooc.fr/media/universities/logoRVB_UPDescart_USPC_2016_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ParisDescartes_7_1-1.jpg",
    },
    {
      id: 228,
      name: "Institut National des Langues et Civilisations Orientales",
      code: "Inalco",
      logo: "https://www.fun-mooc.fr/media/universities/logo-inalco.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau-inalco.png",
    },
    {
      id: 252,
      name: "Montpellier SupAgro",
      code: "supagro",
      logo: "https://www.fun-mooc.fr/media/universities/logo_supagro_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_supagro.jpg",
    },
    {
      id: 313,
      name: "Université Paris-Dauphine ",
      code: "dauphine",
      logo: "https://www.fun-mooc.fr/media/universities/Dauphine_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/illustration_dauphine_980x200.png",
    },
    {
      id: 63,
      name: "Université Bordeaux Montaigne",
      code: "bordeauxmontaigne",
      logo: "https://www.fun-mooc.fr/media/universities/ubordeauxmontaigne.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ubordeauxmontaignepano.jpg",
    },
    {
      id: 78,
      name: "AGROCAMPUS OUEST",
      code: "agrocampusouest",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-AGROCAMPUS-OUEST.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/agrocampusouest.jpg",
    },
    {
      id: 93,
      name: "AgroParisTech",
      code: "AgroParisTech",
      logo: "https://www.fun-mooc.fr/media/universities/logagroparistech_RVB_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Banniere_Grignon_ciel_Ph-Joyet.jpg",
    },
    {
      id: 96,
      name: "FERRANDI Paris - l'école française de gastronomie",
      code: "ferrandiparis",
      logo: "https://www.fun-mooc.fr/media/universities/Ferrandi_170x110_grand.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_ferrandi.png",
    },
    {
      id: 154,
      name: "GOBELINS, l'école de l'image",
      code: "gobelins",
      logo: "https://www.fun-mooc.fr/media/universities/logo_gobelins_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/baniere_goblins.png",
    },
    {
      id: 218,
      name: "Institut National Polytechnique de Toulouse",
      code: "INPT",
      logo: "https://www.fun-mooc.fr/media/universities/INP_logo_Quadri_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/INP_Toulouse2_banni%C3%A8re.jpg",
    },
    {
      id: 186,
      name: "Institut Pasteur",
      code: "pasteur",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_seul_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Bandeau_IP_Buste_LP_980x200_V2.png",
    },
    {
      id: 13,
      name: "Université Paris 1 Panthéon-Sorbonne",
      code: "Paris1",
      logo: "https://www.fun-mooc.fr/media/universities/logo_paris1-pantheon-sorbonne_180x100_1.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_paris1-pantheon-sorbonne_980x200.jpg",
    },
    {
      id: 18,
      name: "C2i",
      code: "C2i",
      logo: "https://www.fun-mooc.fr/media/universities/c2i.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 24,
      name: "ENS de Lyon",
      code: "ENSDeLyon",
      logo: "https://www.fun-mooc.fr/media/universities/logo-ens-de-lyon-udl.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/image-bandeau-ENSdeLyon.jpg",
    },
    {
      id: 184,
      name: "ENSTA Paristech",
      code: "ENSTA",
      logo: "https://www.fun-mooc.fr/media/universities/logo_ENSTA_RVB_modif_100_180_.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_FUN_ENSTAParisTech.jpg",
    },
    {
      id: 10,
      name: "Université Paris Nanterre",
      code: "Paris10",
      logo: "https://www.fun-mooc.fr/media/universities/pddkpodglldimppo.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/paris10.f6605d9f5319.jpg",
    },
    {
      id: 118,
      name: "Aix-Marseille Université",
      code: "amu",
      logo: "https://www.fun-mooc.fr/media/universities/logo-amu-170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Aix-Marseille-BANDEAU.jpg",
    },
    {
      id: 168,
      name: "Université de Lorraine",
      code: "lorraine",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO_UL_170x110.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Image_Universite_de_Lorraine.jpg",
    },
    {
      id: 126,
      name: "L'observatoire de la Côte d'Azur",
      code: "oca",
      logo: "https://www.fun-mooc.fr/media/universities/logo-OCA.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 132,
      name: "Université Toulouse - Jean Jaurès",
      code: "UT2J",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO_texte_noir.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau-ministere.png",
    },
    {
      id: 157,
      name: "Université Paul Sabatier - Toulouse III",
      code: "UPS",
      logo: "https://www.fun-mooc.fr/media/universities/logo_ut3-170x110.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/ut3-ps-02_199.png",
    },
    {
      id: 298,
      name: "École Pratique des Hautes Études",
      code: "EPHE",
      logo: "https://www.fun-mooc.fr/media/universities/logo-EPHE-180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Banni%C3%A8re-EPHE.jpg",
    },
    {
      id: 3,
      name: "Centre Virchow-Villermé",
      code: "VirchowVillerme",
      logo: "https://www.fun-mooc.fr/media/universities/virchowvillerme_logo.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/virchowvillerme_banner.jpg",
    },
    {
      id: 4,
      name: "Ecole Polytechnique",
      code: "Polytechnique",
      logo: "https://www.fun-mooc.fr/media/universities/polytechnique_logo_1.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/polytechnique_banner.jpg",
    },
    {
      id: 7,
      name: "Université Bordeaux 3 (ancien nom de Bordeaux Montaigne)",
      code: "Bordeaux3",
      logo: "https://www.fun-mooc.fr/media/universities/bordeaux3.ba00217bb88d.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/bordeaux3.06dbeb93eef7.jpg",
    },
    {
      id: 12,
      name: "Paris 11 (ancien nom de Université Paris Sud)",
      code: "Paris11",
      logo: "https://www.fun-mooc.fr/media/universities/paris11.179729acb398.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/paris11.ea38002e63b9.jpg",
    },
    {
      id: 30,
      name: "Grenoble INP",
      code: "grenobleinp",
      logo: "https://www.fun-mooc.fr/media/universities/Grenoble_INP_1_1.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/banniereGrenobleINP.jpg",
    },
    {
      id: 60,
      name: "Université Nice Sophia Antipolis",
      code: "unice",
      logo: "https://www.fun-mooc.fr/media/universities/logo-UNS.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/Bandeau.jpg",
    },
    {
      id: 66,
      name: "Université Stendhal-Grenoble 3",
      code: "ugrenoble3",
      logo: "https://www.fun-mooc.fr/media/universities/logo-stendhal.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/visuel-Mooc.jpg",
    },
    {
      id: 69,
      name: "ISAE-SUPAERO",
      code: "isaesupaero",
      logo: "https://www.fun-mooc.fr/media/universities/logo-isae-supaero.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Bandeau_%C3%A9tablissement_ISAE.jpg",
    },
    {
      id: 84,
      name: "Université Pierre Mendès France (Grenoble 2)",
      code: "upmf",
      logo: "https://www.fun-mooc.fr/media/universities/logo_UPMF_170x110px.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/UPMF_01.jpg",
    },
    {
      id: 105,
      name: "Université de Montpellier 2 (ancien nom)",
      code: "Montpellier2",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-etablissement_vA2n9Cy.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 116,
      name: "Ecole des hautes études en santé publique",
      code: "EHESP",
      logo: "https://www.fun-mooc.fr/media/universities/ehesp-logo.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ehesp-banniere.png",
    },
    {
      id: 120,
      name: "Université de Bretagne Occidentale",
      code: "UBO",
      logo: "https://www.fun-mooc.fr/media/universities/Nouveau_logo_UBO-Hor-Noir_vecto_Dzrt79V.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/UBO-technopole-980x200.png",
    },
    {
      id: 123,
      name: "Université d'Artois",
      code: "univartois",
      logo: "https://www.fun-mooc.fr/media/universities/UNIV_ARTOIS_LOGO_RVB200x200.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere.jpg",
    },
    {
      id: 145,
      name: "Institut de Physique du Globe de Paris",
      code: "IPGP",
      logo: "https://www.fun-mooc.fr/media/universities/USPCIPGP-1.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/IPGP_nuit.jpg",
    },
    {
      id: 175,
      name: "Université de Franche-Comté",
      code: "univ-fcomte",
      logo: "https://www.fun-mooc.fr/media/universities/logo-ufc_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere980_200.jpg",
    },
    {
      id: 177,
      name: "ENAC",
      code: "enac",
      logo: "https://www.fun-mooc.fr/media/universities/logo_enac-bleu_900x500.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/campus_ENAC3_ydgt5kP.jpg",
    },
    {
      id: 204,
      name: "Université de Caen",
      code: "unicaen",
      logo: "https://www.fun-mooc.fr/media/universities/UNICAEN_LOGO_2016_ecran_100px_vXjmy41.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere-unicaen.png",
    },
    {
      id: 207,
      name: "AgroSup Dijon",
      code: "agrosupdijon",
      logo: "https://www.fun-mooc.fr/media/universities/logo_AgroSup_simple_180x110_pour_FUN.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Photo_Ecole_AgroSup_Dijon_980x200pixels.png",
    },
    {
      id: 212,
      name: "Cirad",
      code: "cirad",
      logo: "https://www.fun-mooc.fr/media/universities/agreenium180x100_HmYBD43.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 215,
      name: "Université de Rennes 1",
      code: "univrennes1",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-UR1-FUN_ZYuUExc.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/UR1-FUN.jpg",
    },
    {
      id: 223,
      name: "Institut Supérieur International du Parfum, de la Cosmétique et de l'Aromatique alimentaire",
      code: "isipca",
      logo: "https://www.fun-mooc.fr/media/universities/ISIPCA-logo-180x100-FUN-MOOC-v2016-06-15.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ISIPCA-banner-980x200-FUN-MOOC-v2016-06-15.png",
    },
    {
      id: 231,
      name: "Université de Valenciennes et du Hainaut-Cambrésis (UVHC)",
      code: "UVHC",
      logo: "https://www.fun-mooc.fr/media/universities/uvhc_logo.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeauUVHC.jpg",
    },
    {
      id: 234,
      name: "Ecole Centrale Lyon",
      code: "eclyon",
      logo: "https://www.fun-mooc.fr/media/universities/UDL_lofgo_UU8gp3k.png",
      detail_page_enabled: true,
      banner: null,
    },
    {
      id: 246,
      name: "Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)",
      code: "UVSQ",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_UVSQ_transp_180x100px72.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/panorama_UVSQ_sept16_EG_980x200px72.jpg",
    },
    {
      id: 270,
      name: "Université Bourgogne Franche-Comté ",
      code: "UBFC",
      logo: "https://www.fun-mooc.fr/media/universities/logo_UBFC_grand_complet.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Image_page_de_garde_Funmooc_Ubfc.png",
    },
    {
      id: 276,
      name: "Université de Lille, Droit et Santé",
      code: "universiteLilleDroitSante",
      logo: "https://www.fun-mooc.fr/media/universities/UL2-linkelin2_180x100.png.180x100_q85.png",
      detail_page_enabled: true,
      banner: null,
    },
    {
      id: 289,
      name: "ENSAE ParisTech",
      code: "ensae",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-ENSAE-100517_EuV4sM8.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ensae2.png",
    },
    {
      id: 334,
      name: "VetAgro Sup",
      code: "vetagrosup",
      logo: "https://www.fun-mooc.fr/media/universities/logo-vetagro_sup-PT.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_vetagro_sup.jpg",
    },
    {
      id: 295,
      name: "Université d'Evry-Val-d'Essonne",
      code: "univ-evry",
      logo: "https://www.fun-mooc.fr/media/universities/logo_evry_180-110.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 292,
      name: "Université Paris 13",
      code: "paris13",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_Univ_Paris_13.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/exterieur_forum980x200px.jpg",
    },
    {
      id: 36,
      name: "Université de Strasbourg",
      code: "Strasbourg",
      logo: "https://www.fun-mooc.fr/media/universities/logo_UNISTRA.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/illustration_etablissement_UNISTRA.jpg",
    },
    {
      id: 55,
      name: "Essec",
      code: "essec",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_Essec.jpg",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/ESSEC_Banni%C3%A8re_2.jpg",
    },
    {
      id: 99,
      name: "Université de Perpignan",
      code: "UPVD",
      logo: "https://www.fun-mooc.fr/media/universities/logo-upvd_180_96_b.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/photo-campus-UPVD-980x199-2.jpg",
    },
    {
      id: 102,
      name: "Université de Cergy Pontoise",
      code: "u-cergy",
      logo: "https://www.fun-mooc.fr/media/universities/Logo-UCP-170-110.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/fond-980-199.jpg",
    },
    {
      id: 192,
      name: "Université Paris-Seine",
      code: "parisseine",
      logo: "https://www.fun-mooc.fr/media/universities/logo_paris_seine_180x100.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/FABLAB_ciel_bleu_FUN_980x200.jpg",
    },
    {
      id: 304,
      name: "Université Côte d'Azur",
      code: "UCA",
      logo: "https://www.fun-mooc.fr/media/universities/logo_uca_180x110_v2.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeau_UCA_980x200_tiO0zfJ.jpg",
    },
    {
      id: 33,
      name: "Université Virtuelle Environnement et Développement durable (UVED) ",
      code: "uved",
      logo: "https://www.fun-mooc.fr/media/universities/logoUVED_fond-clair_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/unnamed_attachment_1.png",
    },
    {
      id: 90,
      name: "Université libre de Bruxelles (ULB)",
      code: "ulb",
      logo: "https://www.fun-mooc.fr/media/universities/logo-ulb.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/ULB_baniere_980x200.jpg",
    },
    {
      id: 148,
      name: "Alliance française Paris Ile-de-France",
      code: "AFPIF",
      logo: "https://www.fun-mooc.fr/media/universities/logo_AFPIF_170x110.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 139,
      name: "École de l'air",
      code: "EcoleAir",
      logo: "https://www.fun-mooc.fr/media/universities/LOGO_ECOLE_DE_LAIR_carr%C3%A9_new.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 171,
      name: "IFOCA",
      code: "IFOCA",
      logo: "https://www.fun-mooc.fr/media/universities/logo_ifoca.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 129,
      name: "Université de Jendouba",
      code: "ujendouba",
      logo: "https://www.fun-mooc.fr/media/universities/UJ_nouveau2.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniereujb3.png",
    },
    {
      id: 264,
      name: "Université de Liège",
      code: "ulg",
      logo: "https://www.fun-mooc.fr/media/universities/logo-ULg_OJtOWgE.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/bandeauULg1.png",
    },
    {
      id: 49,
      name: "Animafac-Cnous",
      code: "animafac-cnous",
      logo: "https://www.fun-mooc.fr/media/universities/logo_Animafac-Cnous_2016_HCNXApo.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 142,
      name: "Ecole Nationale Supérieure de Sécurité Sociale",
      code: "en3s",
      logo: "https://www.fun-mooc.fr/media/universities/logo_en3s_pour_MOOC.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 165,
      name: "Ecole Nationale Supérieure de Céramique Industrielle",
      code: "ensci",
      logo: "https://www.fun-mooc.fr/media/universities/ensci_170x110.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/BANNIERE_FUN_ENSCILIMOGES_980x200.png",
    },
    {
      id: 173,
      name: "Wikimédia France",
      code: "WMFr",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_wikimedia_180x100.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 182,
      name: "Institut Catholique de Paris",
      code: "ICP",
      logo: "https://www.fun-mooc.fr/media/universities/NEW-LOGO_ICP.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 75,
      name: "Université de Genève",
      code: "unige",
      logo: "https://www.fun-mooc.fr/media/universities/logo-unige.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/UNIGE-Banner1-980x200.jpg",
    },
    {
      id: 135,
      name: "Université de Sousse",
      code: "usousse",
      logo: "https://www.fun-mooc.fr/media/universities/LogoUS_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Batiment_US.jpg",
    },
    {
      id: 243,
      name: "Université de Mons",
      code: "UMONS",
      logo: "https://www.fun-mooc.fr/media/universities/_UMONS_rouge_quadri_180x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_umons_2016.png",
    },
    {
      id: 258,
      name: "Ecole Supérieure d'Ingénieurs Léonard de Vinci",
      code: "devinci",
      logo: "https://www.fun-mooc.fr/media/universities/logo_pulv.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/cover_pulv.jpg",
    },
    {
      id: 280,
      name: "Direction des Ressources Humaines de l'Armée de Terre ",
      code: "drhatform",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_DRHAT.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 301,
      name: "Université d'Ottawa",
      code: "uottawa",
      logo: "https://www.fun-mooc.fr/media/universities/logo-ottawa.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/banniere.png",
    },
    {
      id: 319,
      name: "INSPQ",
      code: "INSPQ",
      logo: "https://www.fun-mooc.fr/media/universities/logo-FUN_complet_1_fxL0Grv_hkVxndA.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 327,
      name: "Université de Limoges",
      code: "unilim",
      logo: "https://www.fun-mooc.fr/media/universities/logo_universitelimoges_L71odfY.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Photo_V2.jpg",
    },
    {
      id: 337,
      name: "Direction générale des étrangers en France",
      code: "dgef-interieur",
      logo: "https://www.fun-mooc.fr/media/universities/logo-minint.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_minist.jpg",
    },
    {
      id: 261,
      name: "Fondation Maison des      Sciences de l'Homme",
      code: "fmsh",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_FMSH",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/Banni%C3%A8re.jpg",
    },
    {
      id: 27,
      name: "FUN",
      code: "FUN",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_PLATEFORME_FUN_170x110.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 151,
      name: "CANOPÉ",
      code: "Canope",
      logo: "https://www.fun-mooc.fr/media/universities/Logo_reseauCanope_170x110.jpg",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 237,
      name: "CoR",
      code: "CoR",
      logo: "https://www.fun-mooc.fr/media/universities/CoR-EN.PNG",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 322,
      name: "Le Ministère de l'Enseignement  Supérieur, de la Recherche et de l'Innovation",
      code: "enseignementsup",
      logo: "https://www.fun-mooc.fr/media/universities/ministere.jpg",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/MESRI_funmooc_980x200_01123.jpg",
    },
    {
      id: 2,
      name: "Ecole CentraleSupelec",
      code: "CentraleParis",
      logo: "https://www.fun-mooc.fr/media/universities/logo_centralesupelec_170x110.png",
      detail_page_enabled: true,
      banner: "https://www.fun-mooc.fr/media/universities/centraleparis_banner.jpg",
    },
    {
      id: 21,
      name: "Unisciel",
      code: "Unisciel",
      logo: "https://www.fun-mooc.fr/media/universities/unisciel_1.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 15,
      name: "UPMC",
      code: "UPMC",
      logo: "https://www.fun-mooc.fr/media/universities/upmc.b2172efd19a0.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/upmc.8c5fa9eee5e8.jpg",
    },
    {
      id: 255,
      name: "La conférence des ITII",
      code: "itii",
      logo: "https://www.fun-mooc.fr/media/universities/ITII_LOGO_FILETS_Q-01.jpg",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 267,
      name: "Université de Carthage",
      code: "ucarthage",
      logo: "https://www.fun-mooc.fr/media/universities/logo_carthage.jpg",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 273,
      name: "Ecole du Val de Grace",
      code: "EVDG",
      logo: "https://www.fun-mooc.fr/media/universities/logo-FUN_complet.png",
      detail_page_enabled: true,
      banner: null,
    },
    {
      id: 279,
      name: "Université de la Polynésie Française",
      code: "UPF",
      logo: "https://www.fun-mooc.fr/media/universities/logo-upf-2014-193x110.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 283,
      name: "Institut supérieur de l'électronique et du numérique (ISEN)",
      code: "isentoulon",
      logo: "https://www.fun-mooc.fr/media/universities/yncrea_toulon_v2.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 307,
      name: "Université Ouaga II",
      code: "Ouaga2",
      logo: "https://www.fun-mooc.fr/media/universities/logo_170-110_ouaga2.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/banni%C3%A8re_ouaga2.jpg",
    },
    {
      id: 310,
      name: "Université Paris-Est",
      code: "UPE",
      logo: "https://www.fun-mooc.fr/media/universities/logo_UPE_vignette.png",
      detail_page_enabled: false,
      banner: "https://www.fun-mooc.fr/media/universities/banniere_UPE_980x200.png",
    },
    {
      id: 316,
      name: "AUF_OIF",
      code: "AUF_OIF",
      logo: "https://www.fun-mooc.fr/media/universities/logo-FUN_complet_1_fxL0Grv.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 325,
      name: "Education & Numérique",
      code: "education-et-numerique",
      logo: "https://www.fun-mooc.fr/media/universities/EN.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 326,
      name: "Université de la Réunion",
      code: "univ-reunion",
      logo: "https://www.fun-mooc.fr/media/universities/logo_Univ_r%C3%A9union_180x110.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 330,
      name: "LFB BIOMEDICAMENTS",
      code: "groupe-lfb",
      logo: "https://www.fun-mooc.fr/media/universities/logo-FUN_complet_zGQHMsK.png",
      detail_page_enabled: false,
      banner: null,
    },
    {
      id: 332,
      name: "Université François-Rabelais de Tours",
      code: "univ-tours",
      logo: "https://www.fun-mooc.fr/media/universities/logo-FUN_complet_SuEtZXy.png",
      detail_page_enabled: false,
      banner: null,
    },
  ],
  next: null,
}
