# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedOrganizations',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organizations_featuredorganizations', serialize=False, to='cms.CMSPlugin')),
                ('number', models.IntegerField(default=18, verbose_name='Number of organizations to display')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
